Fix integration scripts type checking
WebOfTrust/signify-ts pull request #104
Opened 2023-09-08 13:55 UTC by psteniusubi

I think there's an anti-pattern in the integration tests in singify-ts/examples 

All of the .ts files start with this declaration
`let signify: any;`

This effectively disables any type checking by the typescript compiler, VS Code and other tools

This pull request is a suggestion how to fix this. If this pattern is acceptable then the other scripts should be fixed as well.

2023-09-08 14:14 UTC, pfeairheller requested changes
Yes, this looks like a good approach.  Please add the fix to all the other scripts and we can get this merged.

2023-09-08 14:39 UTC, psteniusubi commented
@pfeairheller 

If fixed this for make_endroles.ts and list_notifications.ts. However in the latter there is now a compile error that I cannot easily find a solution for

```
list_notifications.ts:74:45 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'Uint8Array'.

74                     let esigs = keeper.sign(nexn.raw)
                                               ~~~~~~~~
```

2023-09-08 14:43 UTC, pfeairheller commented
> @pfeairheller
> 
> If fixed this for make_endroles.ts and list_notifications.ts. However in the latter there is now a compile error that I cannot easily find a solution for
> 
> ```
> list_notifications.ts:74:45 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'Uint8Array'.
> 
> 74                     let esigs = keeper.sign(nexn.raw)
>                                                ~~~~~~~~
> ```

There is a method in Signify called `b` that will convert a string to a Uint8Array, use that on `nextn.raw

2023-09-08 18:50 UTC, psteniusubi commented
Thanks @pfeairheller that was the solution. I also had to change require("prompt-sync") into import. 
I tested and I can complete the multi-sig group inception sequence.
I'll create an other pull request for the scripts in examples/integration-scripts

2023-09-09 19:22 UTC, rodolfomiranda commented
I used the same approach in all scripts under `/examples/integration-scrpts`. PR #105

2023-09-21 14:06 UTC, pfeairheller approved these changes

2023-09-23 11:04 UTC, merged