Integration test for rotating single-sig delegate identifier
WebOfTrust/signify-ts pull request #160
Opened 2023-12-02 09:25 UTC by psteniusubi

The last test is marked as failing. Reproduces issue #159 

Keria stack trace

```
signify-ts-keria-1         | 2023-12-02 09:12:11 [FALCON] [ERROR] PUT /identifiers/delegate1 => Traceback (most recent call last):
signify-ts-keria-1         |   File "/keria/venv/lib/python3.10/site-packages/keri/app/habbing.py", line 2443, in processEvent
signify-ts-keria-1         |     self.kvy.processEvent(serder=serder, sigers=sigers)
signify-ts-keria-1         |   File "/keria/venv/lib/python3.10/site-packages/keri/core/eventing.py", line 2994, in processEvent
signify-ts-keria-1         |     kever.update(serder=serder, sigers=sigers, wigers=wigers,
signify-ts-keria-1         |   File "/keria/venv/lib/python3.10/site-packages/keri/core/eventing.py", line 1940, in update
signify-ts-keria-1         |     raise ValidationError("Attempted non delegated rotation on "
signify-ts-keria-1         | keri.kering.ValidationError: Attempted non delegated rotation on delegated pre = EA8nuk8Z3ZwhL4PmECqNs6w4hUk47RGeiRTn0UKvRf74 with evt = {'v': 'KERI10JSON000160_', 't': 'rot', 'd': 'EA0dFkf7S1w3uJANMeZlcWAzTQRbgqURdjpFxSbjgekk', 'i': 'EA8nuk8Z3ZwhL4PmECqNs6w4hUk47RGeiRTn0UKvRf74', 's': '1', 'p': 'EA8nuk8Z3ZwhL4PmECqNs6w4hUk47RGeiRTn0UKvRf74', 'kt': '1', 'k': ['DLmuY28mF6Golgq2SJVENE4iLXqNc2nMcb7bh6eiLSqZ'], 'nt': '1', 'n': ['ELY_6-spjz3o-ceMXis4i81maZaRgzk45vjVWKMaxOAs'], 'bt': '0', 'br': [], 'ba': [], 'a': []}.
signify-ts-keria-1         |
signify-ts-keria-1         | During handling of the above exception, another exception occurred:
signify-ts-keria-1         |
signify-ts-keria-1         | Traceback (most recent call last):
signify-ts-keria-1         |   File "falcon/app.py", line 365, in falcon.app.App.__call__
signify-ts-keria-1         |   File "/keria/src/keria/app/aiding.py", line 470, in on_put
signify-ts-keria-1         |     op = self.rotate(agent, name, body)
signify-ts-keria-1         |   File "/keria/src/keria/app/aiding.py", line 506, in rotate
signify-ts-keria-1         |     hab.rotate(serder=serder, sigers=sigers)
signify-ts-keria-1         |   File "/keria/venv/lib/python3.10/site-packages/keri/app/habbing.py", line 2404, in rotate
signify-ts-keria-1         |     self.processEvent(serder, sigers)
signify-ts-keria-1         |   File "/keria/venv/lib/python3.10/site-packages/keri/app/habbing.py", line 2445, in processEvent
signify-ts-keria-1         |     raise kering.ConfigurationError(f"Improper Habitat event type={serder.ked['t']} for "
signify-ts-keria-1         | keri.kering.ConfigurationError: Improper Habitat event type=rot for pre=EA8nuk8Z3ZwhL4PmECqNs6w4hUk47RGeiRTn0UKvRf74.
signify-ts-keria-1         |
```

2023-12-09 11:27 UTC, lenkan commented
@psteniusubi and others:

Do we intend to wait with the merge until the functionality is fixed so the test passes for real?

2023-12-09 12:01 UTC, psteniusubi commented
It's a good question. 
Is it better to create a PR like this with the test failing? Then people can see the error from the logs of the CI integration test run.
An other PR like this is here https://github.com/WebOfTrust/signify-ts/pull/157

2023-12-15 19:25 UTC, m00sey commented
> Is it better to create a PR like this with the test failing? 

I'd rather have an issue, with a link to a fork with the failing test.

When I see PRs I think "mergable code".

2024-01-17 00:49 UTC, pfeairheller requested changes
The library needs `drt` support.

2024-01-17 00:49 UTC, pfeairheller commented on examples/integration-scripts/singlesig-drt.test.ts
> +            s: 0,
This sn value needs to be a string like '0'

2024-01-17 00:49 UTC, pfeairheller commented on examples/integration-scripts/singlesig-drt.test.ts
> +        let result = await client2.identifiers().rotate('delegate1', kargs);
This `rotate` method does not support `drt` event types for delegated identifiers.  It will need to be enhanced to support delegated AIDs

2024-01-17 15:45 UTC, pfeairheller commented
I'm going to add drt support to the library and then retry this test.

2024-01-18 19:15 UTC, pfeairheller commented
I reintroduced this test in #197 where I also fixed the other delegation integration tests.  Closing this no in favor of that one.  Thanks for the script!!

2024-01-18 19:15 UTC, closed without merging