Problem with delegated multisig group
WebOfTrust/signify-ts pull request #184
Opened 2024-01-03 01:33 UTC by nkongsuwan

To issue a QVI vLEI credential, a delegating AID must issue the credential to a delegated multisig group AID. I made an update to `delegation-multisig.test.ts` to demonstrate three problems with delegated multisig AID. Hopefully, the ongoing work in Keripy will solve these problems.

- [ ] On Line #L59 to #L67, delegated multisig group will not be created with witnesses. This is related to issue #145. 
- [ ] On Line #L102, the delegator cannot resolve the OOBI of the delegated multisig group.
- [ ] The delegator and delegated multisig group cannot send IPEX messages to each other. (This might not actually be  a problem, but I could get it to work.)

2024-01-04 15:15 UTC, m00sey commented
Pending an update from @pfeairheller

2024-01-10 05:53 UTC, nkongsuwan commented
@m00sey I have linked the PR to three separate issues.

2024-01-15 20:20 UTC, pfeairheller commented
I've been able to successfully create multisig AIDs, issue credentials and perform IPEX GRANT and ADMIT messages from SigPy.  I have not included delegation.  I will start trying to see what is breaking here in SigTS but may have to run through it all in SigPy first.

2024-01-17 00:53 UTC, pfeairheller requested changes
Please create this test as a new file and new test and then rebase this so we can see if it works.

2024-01-17 14:36 UTC, nkongsuwan commented
@pfeairheller All issues related to this PR seem to have been resolved. I have also converted the script into a new file. Over the next few days, I will try to work on this test script further to issue all the way to an ECR vLEI credential using 2 GARs, 3 QARs, 3 LARs, and 1 ECR person.

2024-01-23 00:59 UTC, nkongsuwan commented
I might not get to this in a while. I will close this for now to make another PR when I actually finish it.

2024-01-23 00:59 UTC, closed without merging