Add registry GET
WebOfTrust/signify-ts pull request #189
Opened 2024-01-06 19:04 UTC by kentbull

KERIA supports a GET for a Registry. This will simplify checking if a registry exists or not and getting its details. Since we have `registries.list()` we may as well have `registries.get()`.

2024-01-07 12:47 UTC, lenkan requested changes
Sounds reasonable to me!

Formatting and testing fails. Otherwise I just had some minor comments/questions.

2024-01-08 14:55 UTC, kentbull commented on src/keri/core/core.ts
> +export interface Registry {
That works. I thought it may make sense to put all interfaces in some core module, though credentialing.ts works just fine. I'll move it there.

2024-01-08 14:56 UTC, kentbull commented on examples/integration-scripts/credentials.test.ts
>          const registry: { name: string; regk: string } = registries[0];
I agree, it is redundant. I just wanted to make it clear what was being replaced. I'll remove the old one.

2024-01-08 14:56 UTC, kentbull commented on examples/integration-scripts/credentials.test.ts
> +            return reg;
agreed

2024-01-08 16:54 UTC, kentbull commented
Looks like the current error is due to a mismatch of the version of KERIA in the Docker Hub image and the **development** branch of KERIA. This PR will be in draft state until a current KERIA image is pushed.

Docker compose logs:
```
[FALCON] [ERROR] GET /identifiers/issuer/registries/vLEI-test-registry => Traceback (most recent call last):
keria-1         |   File "falcon/app.py", line 365, in falcon.app.App.__call__
keria-1         |   File "/keria/src/keria/app/credentialing.py", line 223, in on_get
keria-1         |     state=registry.tever.state().ked
keria-1         | AttributeError: 'RegStateRecord' object has no attribute 'ked'
```

2024-02-13 14:34 UTC, pfeairheller commented
Closing this PR since it is a month old.  Please open a new one to add this functionality

2024-02-13 14:34 UTC, closed without merging