signedFetch more generic/configurable aligning it with fetch api
WebOfTrust/signify-ts pull request #259
Opened 2024-05-08 13:06 UTC by 2byrds

2024-05-08 13:15 UTC, lenkan reviewed
Had a quick look with some initial questions, will try it out later.

2024-05-08 13:15 UTC, lenkan commented on src/keri/app/clienting.ts
> +        let headers = req.headers;
Should be enough with `const headers = new Headers(req.headers)` I think?

2024-05-08 13:15 UTC, lenkan commented on src/keri/app/clienting.ts
> +            headers.get('method')!,
Should this not be `req.method` or actually `req.method ?? "GET"` because GET should be the default?

2024-05-08 17:30 UTC, 2byrds commented on src/keri/app/clienting.ts
> +        let headers = req.headers;
nice! fixed.

2024-05-08 17:32 UTC, 2byrds commented on src/keri/app/clienting.ts
> +            headers.get('method')!,
totally should. i updated the clienting.test to check the header signature in hopes of catching mistakes like that.

2024-05-12 08:17 UTC, lenkan requested changes
Sorry for the delay.

I had some very minor suggestions but I think it looks good otherwise.

2024-05-12 08:17 UTC, lenkan commented on src/keri/app/clienting.ts
>          path: string,
```suggestion
        url: string,
```

I personally don't see a value in separating these args. In fetch which is a familiar API you do not separate the host and the path. They are both part of the URL.

2024-05-12 08:17 UTC, lenkan commented on src/keri/app/clienting.ts
>       * @param {string} path Path to the resource
```suggestion
     * @param {string} url URL of the resource
```

2024-05-12 08:17 UTC, lenkan commented on src/keri/app/clienting.ts
>          path: string,
To get the for the signature you can simply do `const pathname = new URL(url).pathname`. This also strips the query params so the `path.slit["?"]` is not needed on L272

2024-05-14 16:35 UTC, 2byrds commented on src/keri/app/clienting.ts
>          path: string,
I think whoever defined the method signature was trying to explicitly align with https://datatracker.ietf.org/doc/html/rfc9421#name-path but i'm okay with aligning with fetch and having the method handle the url parts as you specified. Let me know if the RFC alignment alters your thoughts.

Also, browser extensions that use signify-ts should sign headers the same way as signify-ts, but they don't do the fetch. So I'll refactor this method to take a url but not do the fetch. Let me know if you have thoughts on that.

2024-05-14 16:58 UTC, lenkan commented on src/keri/app/clienting.ts
>          path: string,
Yeah, good idea. I think that makes sense. So you basically return a "signed" RequestInit? Imo, that makes it much more useful.

If you make sure the `createSignedRequest` returns a `Request` (available as a type in the global namespace in both node.js and browsers), the following usage would be supported and be very  straightforward for anyone to use.


```typescript
   // SignifyClient
   async createSignedRequest(aidName: string, url: string, requestInit: RequestInit): Promise<Request> {
   }
  

const request = await client.createSignedRequest("aidname", url, initialRequestInit);
await fetch(request)
```

2024-05-14 17:01 UTC, 2byrds commented on src/keri/app/clienting.ts
>          path: string,
> Yeah, good idea. I think that makes sense. So you basically return a "signed" RequestInit? Imo, that makes it much more useful.
> 
> If you make sure the `createSignedRequest` returns a `Request` (available as a type in the global namespace in both node.js and browsers), the following usage would be supported and be very straightforward for anyone to use.
> 
> ```ts
>    // SignifyClient
>    async createSignedRequest(aidName: string, url: string, requestInit: RequestInit): Promise<Request> {
>    }
>   
> 
> const request = await client.createSignedRequest("aidname", url, initialRequestInit);
> await fetch(request)
> ```

great! working on  that update now

2024-05-14 23:50 UTC, 2byrds commented
@lenkan latest changes per your recommendations have been added.

2024-05-15 06:34 UTC, lenkan commented on examples/integration-scripts/singlesig-vlei-issuance.test.ts
> +    minSleep: 1000,
I suppose this change is because with the previous settings, we did maximum 5 retries with a timeout that exponentially increased from 10ms to 1000ms which would yield something that is a lot less than 5 seconds.

A problem with this setting is that the timeout value does not make a difference, since the maxRetries is set to 5 and both minSleep and maxSleep is 1000ms, the retry will timeout at 5*1000ms = 5 seconds

Maybe something like this is better if you need a timeout of 30s (I doubt we need 30s though, maybe 10s is enough)

- minSleep: 100
- maxRetries: undefined
- timeout: 30000

But it is not important, you would only gain maximum one second. I was just curious of this change.

2024-05-15 06:37 UTC, lenkan reviewed
Looks really good. Some minor adjustments to the js docs, they were left with the original description so they would be misleading to consumers of the library.

2024-05-15 06:37 UTC, lenkan commented on src/keri/app/clienting.ts
>       * Fetch a resource from from an external URL with headers signed by an AID
```suggestion
     * Create a Signed Request to fetch a resource from an external URL with headers signed by an AID
```

2024-05-15 06:37 UTC, lenkan commented on src/keri/app/clienting.ts
> +     * @returns {Promise<Request>} A promise to the result of the fetch
```suggestion
     * @returns {Promise<Request>} A promise to the created Request
```

2024-05-15 12:02 UTC, 2byrds commented
thank you for fixes @lenkan i have updated it per your suggestions

2024-05-16 13:03 UTC, 2byrds commented on package.json
> +  "version": "0.2.2",
I wanted to signal this is a significant change. Happy to handle that however u suggest

2024-05-16 13:53 UTC, lenkan commented on package.json
> +  "version": "0.2.2",
I think the version can be bumped in separate PR. The packages is published manually now anyway and I think the version is bumped using `npm version`. So I vote for leaving this part out of this PR. Could add a "Breaking: " prefix to the PR though.

2024-05-16 14:26 UTC, lenkan approved these changes
LGTM

2024-05-16 14:31 UTC, merged